[package]
name = "octree"
version = "0.1.0"
authors = ["Lyon Beckers <lyon@nylonblonde.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
